-- identifiying the grain of the table
SELECT 
GAME_ID, TEAM_ID, PLAYER_ID, COUNT(3) FROM GAME_DETAILS
GROUP BY 1,2,3
HAVING COUNT(3)>1
--SO THE GRAIN IS SUPPOSED TO BE UNIQUE
--THIS IS THE SCENAIRO WHERE WHENLOGGIN THERE IS A CHANCE OF DOUBLE DATABASE
-- DEDUPE THIS

--DEDUPE QUERY
WITH DEDUPED AS(
    SELECT *, ROW_NUMBER() OVER (PARTITION BY GAME_ID, TEAM_ID,PLAYER_ID) AS ROW_NUM
     FROM game_details
)
SELECT * FROM DEDUPED
WHERE ROW_NUM = 1



--DEDUPE BUT IN DATA SENSE OF CHOOSING THE RIGHT RECORD
WITH DEDUPE AS(
    SELECT
    G.GAME_DATE_EST,
    G.SEASON,
    G.HOME_TEAM_ID,
    G.visitor_team_id,
    GD.*,
    ROW_NUMBER() OVER(PARTITION BY GD.GAME_ID, GD.TEAM_ID, GD.player_id ORDER BY G.game_date_est) AS ROW_NUM
    FROM
    GAME_DETAILS GD JOIN GAMES G ON G.GAME_ID = GD.game_id
)
INSERT INTO fct_game_details
SELECT 
    GAME_DATE_EST,
    SEASON,
    TEAM_ID,
    PLAYER_ID,
    PLAYER_NAME,
    START_POSITION,
    TEAM_ID = HOME_TEAM_ID AS DIM_IS_PLAYING_AT_HOME,
    COALESCE(POSITION('DNP' IN COMMENT),0)>0 AS DIM_DID_NOT_PLAY,
    COALESCE(POSITION('DND' IN COMMENT),0)>0 AS DIM_DID_NOT_DRESS,
    COALESCE(POSITION('NWT' IN COMMENT),0)>0 AS DIM_DID_NOT_WITH_TEAM,
    CAST(SPLIT_PART(MIN, ':', 1)AS REAL) + CAST(SPLIT_PART(MIN, ':', 2) AS REAL)/60 AS M_MINUTES,
    FGM AS M_FGM,
    FGA AS M_FGA,
    FG3M AS M_FG3M,
    FG3A AS M_FG3A,
    FTM AS M_FTM,
    FTA AS M_FTA,
    OREB AS M_OREB,
    DREB AS M_DREB,
    REB AS M_REB,
    AST AS M_AST,
    STL AS M_STL,
    BLK AS M_BLK,
    "TO" AS M_TURNOVER,
    PF AS M_PF,
    PTS AS M_PTS,
    plus_minus AS M_PLUS_MINUS
FROM DEDUPE
WHERE ROW_NUM =1;


--ddl to create fact table
CREATE TABLE FCT_GAME_DETAILS(
    DIM_GAME_DATE DATE,
    DIM_SEASON INTEGER,
    DIM_TEAM_ID INTEGER,
    DIM_PLAYER_ID INTEGER,
    DIM_PLAYER_NAME TEXT,
    DIM_START_POSITION TEXT,
    DIM_IS_PLAYING_AT_HOME BOOLEAN,
    DIM_DID_NOT_PLAY BOOLEAN,
    DIM_DID_NOT_DRESS BOOLEAN,
    DIM_NOT_WITH_TEAM BOOLEAN,
    M_MINUTES INTEGER,
    M_FGM INTEGER,
    M_FGA INTEGER,
    M_FG3M INTEGER,
    M_FG3A INTEGER,
    M_FTM INTEGER,
    M_FTA INTEGER,
    M_OREB INTEGER,
    M_DREB INTEGER,
    M_REB INTEGER,
    M_AST INTEGER,
    M_STL INTEGER,
    M_BLK INTEGER,
    M_TURNOVER INTEGER,
    M_PF INTEGER,
    M_PTS INTEGER,
    M_PLUS_MINUS INTEGER,
    PRIMARY KEY(DIM_GAME_DATE, DIM_TEAM_ID, DIM_PLAYER_ID)
)

--CHECK LOAD
SELECT * FROM fct_game_details;


--ANALYTIC QUERY TO undestanding the blurry line between dim and fact data
SELECT
    DIM_PLAYER_NAME,
    COUNT(1) AS NUM_OF_GAMES,
    COUNT(CASE WHEN DIM_NOT_WITH_TEAM THEN 1 END) AS BAILED_NUM,
    CAST(COUNT(CASE WHEN DIM_NOT_WITH_TEAM THEN 1 END) AS REAL)/CAST(COUNT(1) AS REAL) AS BAIL_PERCENTAGE
FROM FCT_GAME_DETAILS
GROUP BY 1
ORDER BY 4 DESC;