--QUERYING THE EVENTS TABLE
SELECT * FROM EVENTS;

--DDL FOR USERS CUMULATED - CUMULATED ENTRIES FOR USERS DATA OF A WEBSITE
DROP TABLE users_cumulated;
CREATE TABLE USERS_CUMULATED(
    USER_ID TEXT,
    DATES_ACTIVE DATE[],
    CURR_DATE DATE,
    PRIMARY KEY(USER_ID, CURR_DATE)
);

--GETTING THE DATE RANGE FOR LOADING THE CUMULATIVE TABLE
SELECT MIN(EVENT_TIME), MAX(EVENT_TIME) FROM EVENTS;


-- INCREMENTAL QUERY TO LOAD CUMULATIVE TABLE
WITH YESTERDAY AS (
    SELECT *
    FROM users_cumulated
    WHERE CURR_DATE = DATE('2023-01-30')
),
TODAY AS(
    SELECT 
    CAST(USER_ID AS TEXT) AS USER_ID,
    DATE(CAST(EVENT_TIME AS TIMESTAMP)) AS DATE_ACTIVE
    FROM events
    WHERE DATE(CAST(EVENT_TIME AS TIMESTAMP)) = DATE('2023-01-31')
    AND USER_ID IS NOT NULL
    GROUP BY USER_ID, DATE(CAST(EVENT_TIME AS TIMESTAMP))
)
INSERT INTO users_cumulated
SELECT 
COALESCE(YT.USER_ID, TD.USER_ID) AS USER_ID,
CASE
    WHEN TD.DATE_ACTIVE IS NULL THEN YT.DATES_ACTIVE
    ELSE ARRAY[TD.DATE_ACTIVE]||YT.DATES_ACTIVE
END AS DATES_ACTIVE,
COALESCE(TD.DATE_ACTIVE, YT.CURR_DATE + INTERVAL '1 DAY') AS CURR_DATE
FROM YESTERDAY YT 
FULL OUTER JOIN TODAY TD
ON YT.USER_ID = TD.USER_ID;

--CHECK LOADED DATA
SELECT * FROM users_cumulated
WHERE CURR_DATE = DATE('2023-01-31');


--ANALYTIC QUERY TO GENERATE DATES ACTIVE ONTO A BINARY FORM SIMILAR TO SAYING '1' FOR A ACTIVE DAY OF 30 BITS
WITH SERIES AS (
    SELECT
    GENERATE_SERIES(
        DATE('2023-01-01'),
        DATE('2023-01-31'),
        INTERVAL '1 DAY'
    ) AS DATE_SERIES
),
USERS AS (
    SELECT * FROM users_cumulated
    WHERE CURR_DATE = DATE('2023-01-31')
),
PLACEHOLDER_INTS AS(
    SELECT
    CURR_DATE - DATE(DATE_SERIES),
    CASE WHEN 
        DATES_ACTIVE @> ARRAY[DATE(DATE_SERIES)]
        THEN CAST(POW(2, 32 - (CURR_date - date(date_series))) AS BIGINT)
        else 0
    END as placeholder,
    *
FROM USERS CROSS JOIN SERIES
)
--******IMP QUERY TO GENRATE ACTIVE FLAGS THE BEST WAY
SELECT
USER_ID,
SUM(PLACEHOLDER),
CAST(CAST(SUM(PLACEHOLDER) AS BIGINT)AS BIT(32)),
BIT_COUNT(
    CAST(CAST(SUM(PLACEHOLDER) AS BIGINT)AS BIT(32))
    ) > 0  AS DIM_IS_MONTHLY_ACTIVE,
BIT_COUNT(
    cast('11111110000000000000000000000000' as BIT(32))&
    CAST(CAST(SUM(PLACEHOLDER) AS BIGINT)AS BIT(32))
) > 0 AS DIM_IS_MONTHLY_ACTIVE,
BIT_COUNT(
    cast('10000000000000000000000000000000' as BIT(32))&
    CAST(CAST(SUM(PLACEHOLDER) AS BIGINT)AS BIT(32))
) > 0 AS DIM_IS_DAILY_ACTIVE
FROM PLACEHOLDER_INTS
GROUP BY USER_ID